import {
  CLOSE_HARNESS_SESSION_ROUTE,
  CREATE_HARNESS_SESSION_ROUTE,
  GET_HARNESS_SESSION_ROUTE,
  LIST_HARNESS_SESSIONS_ROUTE,
} from '../../handlers/harness';

export const HARNESS_ROUTES = [
  LIST_HARNESS_SESSIONS_ROUTE,
  CREATE_HARNESS_SESSION_ROUTE,
  GET_HARNESS_SESSION_ROUTE,
  CLOSE_HARNESS_SESSION_ROUTE,
] as const;
